### ISSUE TITLE
Warnings feature/UI for international version

### ISSUE THREAD

**Issue by leijoil** [fmidev/weather-app#349]
Warnings feature based on CAP-feed that is provided by local SmartMet Server.

TODO: detailed specification of warnings feature

**Comment by leijoil** [comment]
![Warnings definitions](https://user-images.githubusercontent.com/19765250/189844731-adf63296-dc7b-4e3f-9971-2285a3f03f32.png)

**Comment by AnttiRumpunen** [comment]
tämä palastellaan pieniin palasiin ja puuhastellaan niitä. Olkoot auki siihen asti.

**Comment by AnttiRumpunen** [comment]
Suljen tämän, koska varoitusten määrittelyistä tehty uusia tikettejä pienempinä palasina.
