### ISSUE TITLE
CI pipeline (international support)

### ISSUE THREAD

**Issue by leijoil** [fmidev/weather-app#350]
Automatic CI pipeline which includes automatisation of delivery process for the application. Both iOS and Android should be covered. Pipeline can be implemented in any country, which means all country specific variables should be configurable.

**Comment by AnttiRumpunen** [comment]
Afaik, this is done?

**Comment by evnurm-cgi** [comment]
PR #412 contains the CI/CD pipeline workflow definition (GitHub Actions YAML + Fastlane files).
