### ISSUE TITLE
International date and time formatting

### ISSUE THREAD

**Issue by leijoil** [fmidev/weather-app#370]
- Time should be shown in AM/PM format in addition to 24 hours format
- 3 letter weekday format instead of 2 (Mo --> Mon)
- Date in international format, with 3 letter month abbreviation (Mon 19.9. --> Mon 19 Sep / Mon Sep 19).
     - In addition, date without weekday (19.9. --> 19 Sep)

**Comment by oksman** [comment]
Do we need UI for switching between 12 and 24 hour formats?

Is the date format related to language or the country?
