### ISSUE TITLE
Havaintoaseman graafit: näytetään vain ne mistä on arvoja saatavilla

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#415]
Ilmeisesti näyttää aina kaikki. Näytetään mieluummin ne mistä saa jotain käppyrää.

**Comment by evnurm-cgi** [comment]
Tämän pitäisi korjaantua seuraavan PR:n yhteydessä (tehty tikettiä #414 varten): https://github.com/fmidev/weather-app/pull/421

**Comment by AnttiRumpunen** [comment]
Tämä ok. #414 ei.

**Comment by evnurm-cgi** [comment]
Tämä tiketti voidaan sulkea, #414 on suljettu, mutta pitäisi tarkistaa, ovatko sen kommenteissa esitetyt havainnot vielä voimassa.
