### ISSUE TITLE
Havainnot: pilvisyys 9/8 -case

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#419]
9/8 tarkoittaa ettei pilvisyyttä voitu määrittää sumun tms takia. Ei kuitenkaan tarkoita puuttuvaa arvoa. Korjaus tulee edellisiin havaintoihin sekä graafiin. Graafin maksimi voi kuitenkin olla 8/8 eli siellä ei tarvitse näkyä 9/8 käppyrässä eli käytännössä taitaa 9/8 = 8/8. Listamuotoisessa esityksessä tulee kuitenkin olla 9/8.

Lokalisoinnit teksteille:
fi = ei voitu määrittää
en = sky obscured
ev = kan inte anges

**Comment by evnurm-cgi** [comment]
Tutkiskelin asiaa ja näyttää siltä, että ainakin havaintolistauksessa näkyy 9/8 ja graafissakin maksimi näyttäisi olevan 8/8 eikä arvo näytä graafista puuttuvan tuolta kohdalta, jossa arvo on 9/8.

![Image](https://user-images.githubusercontent.com/107606457/221503022-5b43174e-43b5-4756-b2dc-b436cf67d6c5.jpg)
![Image](https://user-images.githubusercontent.com/107606457/221503023-005405c4-c62b-4476-97ef-535080edcb47.jpg)

Onko olemassa esimerkkiä, jossa tämä toimii väärin (vai olenko vain ymmärtänyt itse väärin)?

**Comment by AnttiRumpunen** [comment]
Ok, täytyy tsekkaa jahka tulee 9/8 -arvoja jostain mittarista.

**Comment by LeaSaukkonen** [comment]
Kokonaspilvisyysessä lukema 9/8 tarkoittaa että pilvisyyttä ei voida mitata esim. sumun takia.
Se siis on ihan oikea mittaus. Mutta tuottaa ongelmaa juuri näissä visualisoinneissa. Jos mahdollista, niin minusta paras ratkaisu olisi muuntaa 9/8 aina 8/8 tulkinnaksi.


Lähetetty sovelluksesta Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Lähettäjä: AnttiRumpunen ***@***.***>
Lähetetty: Wednesday, March 1, 2023 8:52:18 AM
Vastaanottaja: fmidev/weather-app ***@***.***>
Kopio: Subscribed ***@***.***>
Aihe: Re: [fmidev/weather-app] Havainnot: pilvisyys 9/8 -case (Issue #419)


Ok, täytyy tsekkaa jahka tulee 9/8 -arvoja jostain mittarista.

**Comment by AnttiRumpunen** [comment]
Tämä ok main haarassa (android + iOS).
