### ISSUE TITLE
Jamaikan varoitus-ikonit

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#428]
Pyydetty KV-puolelta ikoneita seuraavilla spekseillä:
- koko 38px x 38 px 
- formaattina PNG (1x, 2x ja 3x tarkkuudella) sekä SVG
- mustana sekä valkoisena

Sijoitetaan paikkaan X, josta sovellus voi niitä hakea.

**Comment by AnttiRumpunen** [comment]
@evnurm-cgi Onko toivetta mihin ikonit kannattaa sijoittaa?

**Comment by evnurm-cgi** [comment]
Tällä hetkellä sovelluksessa on käytetty varoitusikoneihin `WarningsSymbol`-komponenttia (https://github.com/fmidev/weather-app/blob/main/src/components/warnings/WarningsSymbol.tsx), joka puolestaan käyttää sisäisesti `Icon`-komponenttia (https://github.com/fmidev/weather-app/blob/main/src/components/common/Icon.tsx). Tällä hetkellä kaikki käytettävissä olevat ikonit on importattu `Icon`-komponentin koodissa kansiosta `src/assets/images/icons`, joten olisi ehkä helpointa laittaa ikonit sinne ja päivittää importit Jamaikan repossa.

Toisaalta tuo vaatisi `Icon`-komponenttien divergoitumista päärepon ja forkin välillä. Mietin vielä, olisiko tuohon jokin parempi ratkaisu.

**Comment by AnttiRumpunen** [comment]
sääsymbolit ovat kuulemma ok eikä tarvitse tehdä mitään.

**Comment by AnttiRumpunen** [comment]
sääsymbolithan ovat ihan eri asia kuin varoitus... Otetaan takaisin listoille. Kyselty mahdollisten varoitustyyppien perään + ikonit niille + miten varoitukset tunnistetaan CAP-sanomista.

**Comment by AnttiRumpunen** [comment]
Nyt on vihdoin saatu varoitussymboleita.
