### ISSUE TITLE
Jamaika: 10 pv ennusteen-selitteet

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#441]
- [x] The description of the wind speed symbol  should be corrected to read “wind speed (km/h)” instead of “wind direction and speed (km/h)”
- [x] the wind gust symbol should be in km/h
- [ ] If possible, the BReTCAT symbols for wind direction should be used on the forecast screen of the app instead of the simple arrows used in the FMI Finland app
- [ ] tuulen nopeuden rajat menee kahdelle riville eli esim. 48-72km/h:ssa h tippuu toiselle riville. Annetaan siis enempi tilaa raja-arvoille. Tällöin selite saattaa mennä kahdelle riville, mutta ei voi mitään. 73-115km/h ja > 115km/h pitää myös mahtua yhdelle riville.
- [x] korvataan breeze -sana wind-sanalla selitteessä eli light/moderate/strong wind.
- [x] Suhteellisen kosteuden teksti pitäisi olla Hum% eikä RH%.
- [x] Päivänpituus: ei tarvita polar night tai midnight sun tai day length-tekstejä eikä ikoneita.
- [x] Päivänpituus poistetaan myös 10pv ennusteesta
- [x] Weather symbols currently in effect -otsikko muutetaan Weather icons used in forecasts -otsikoksi ja näytetään kaikki ikonit eikä vain voimassa olevia
- [x] Thunderstorm ikonit on jotenkin vääristyneitä. En tiedä miten - kysytty lisätietoja
- [ ] Scattered showers ikonit eivät mätsää eli yö ja päivä -ikoneiss eri määrä pisaroita ja pilven tummuus on eri.
- [ ] Very heavy rain -ikoni + selite puuttuu kokonaan
- [ ] Rain showers -selite on kahdesti listoilla
- [ ] Light rain -selite on kahdesti listoilla. Toinen on kai drizzle ja se pitäisi poistaa kokonaan.
- [ ] Partly cloudy taitaapi puuttua kokonaan

**Comment by evnurm-cgi** [comment]
Päivän pituudelle on tehty tiketti, jossa sen (ja siihen liittyvien parametrien) näyttäminen tehdään konfiguroitavaksi, jolloin päivän pituuden saa otettua käyttöön/pois käytöstä tekemättä muutoksia sovelluksen koodiin.
