### ISSUE TITLE
Auringon lasku- ja nousutajoissa virhe?

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#459]
Tarkistetaan seuraava:

Hei,
Pyytäisin korjaamaan ohjelmavirheen koskien auringon nousu- ja laskuaikoja:
Ajat ovat muuten kunnossa sekä paikan että päivän suhteen, mutta jos tarkastelee näyttöä keskiyön tienoilla tuntia ennen ja jälkeen päivän vaihtoa (23:00 - 00:59) jämähtävät nousu- ja laskuajat “vanhan” päivän mukaisina myös koko “uudelle” päivälle. Tilanne korjaantuu vasta kun kello on ehtinyt 01:00 ohi.
Tämä virhe ei toistu tulevien keskiöiden tunteina, vaan ainoastaan käsillä olevan päivänvaihdon kummallakin puolella olevina tunteina.

**Comment by evnurm-cgi** [comment]
Tutkin asiaa ja huomasin, että sovelluksen käyttämät sunrise- ja sunset-arvot ovat vielä keskiyön jälkeen pari tuntia edellisen päivän arvoja. Näyttää siltä, että tällä hetkellä välillä 00:00-02:00 nuo arvot ovat edeltävänä päivänä ja vasta 03:00 alkaen arvot päivittyvät kyseiselle päivälle. 

![Image](https://github.com/fmidev/weather-app/assets/107606457/e42df689-f618-44d4-8e13-157df363a283)

Näkisin, että nämä olisi hyvä saada tulemaan oikein palvelimelta, mutta on toki mahdollista muuttaa koodiakin hakemaan tiedon ajankohdasta, jolla pitäisi olla oikeat arvot.

**Comment by AnttiRumpunen** [comment]
Laitetaan hakemaan klo 06 tms

**Comment by AnttiRumpunen** [comment]
Itseasiassa tuossa taitaa olla ongelmana se, että haku tehdään tz=utc -parametrin kanssa eli 
http://smartmet.fmi.fi/timeseries?producer=default&param=localtime,sunrise,sunset&geoid=6945597&starttime=1696968000&format=debug tuottaa tuloksia missä localtimen ollessa 00 sunrise ja sunset ovat samoja koko päivälle.

http://smartmet.fmi.fi/timeseries?producer=default&param=localtime,sunrise,sunset&geoid=6945597&starttime=1696968000&format=debug&tz=utc -haussa taas sunrise ja sunset arvot on edellisen päivän arvoja 00-02 ja 03 vasta oikein.

**Comment by AnttiRumpunen** [comment]
https://github.com/fmidev/weather-app/pull/510
