### ISSUE TITLE
Check how IOS (Android) handles location names

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#568]
When map is loaded IOS places location names on top of WMS-layers. However, when map is panned location names go below WMS-layers. They should stay on top. Check is there similar functionality on Android as well, enable it if available.

"VectorTile Label" is probably what it's all about...

In Android, locations names are not loaded at all until user zooms in or out. Then they stay on top. At least on 4.1.0.

**Comment by geosaaga** [comment]
react-native-maps has following code

`[_map addOverlay:self level:MKOverlayLevelAboveLabels];`

according to documentation 

https://developer.apple.com/documentation/mapkit/mkoverlaylevel

this means

`Place the overlay above map labels, shields, or point-of-interest icons but below annotations and 3D projections of buildings.`

should have AboveRoads instead that means

`Place the overlay above roadways but below map labels, shields, or point-of-interest icons.`

But the change should be done to react-native-maps codebase.

**Comment by AnttiRumpunen** [comment]
Do nothing for now...
