### ISSUE TITLE
Update react-native-maps

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#570]
Update to next major version (1.15.4 or newer). Currently we are using 0.31.1.

**Comment by geosaaga** [comment]
https://github.com/fmidev/weather-app/pull/572

iOS was pretty easy, but Android required some changes because geolocation didn't work out-of-the-box and marker for user location was blinking at least in debug mode.

**Comment by AnttiRumpunen** [comment]
Downgrade to 1.5.0 since at least 1.9.1 onwards there was memory issues. 1.5.0 is safe.
