### ISSUE TITLE
Investigate and fix timeseries queries when app starts

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#576]
App seems to fire over 10-15 Axios calls during startup.

Especially forecast and observation axios calls need a closer look, they are fired at least 3 times resulting 6-9 calls depending on selected obs station. Rest (dynamic config/announcements/warnings...) seems to be called once.

**Comment by geosaaga** [comment]
Two reasons were found

1. New geolocation caused exta queries even location remained same -> fixed in PR
2. WeatherScreen is mounted twice during startup and both mounts generate queries. More complex issue and created new ticked for it https://github.com/fmidev/weather-app/issues/580
