### ISSUE TITLE
Latest observations listed in varying order

### ISSUE THREAD

**Issue by sirviot** [fmidev/weather-app#588]
List of weather observations may sometimes start in ascending order so that the oldest observation in listed on top. This should be the other way around so that the list starts from the latest observation time.

Attached image shows 26.6.2024 12.00 observation which is followed by 23.6. 13.00 observations. It should begin the list from  26.6. 11.00 observation.

<img src="https://github.com/fmidev/weather-app/assets/23695609/61cc3cf2-30c3-4532-be43-f2b4289025f8" width="200">

**Comment by geosaaga** [comment]
PR: https://github.com/fmidev/weather-app/pull/589
