### ISSUE TITLE
Update Android version to API level 34

### ISSUE THREAD

**Issue by geosaaga** [fmidev/weather-app#590]
According to Google:

Starting August 31, 2024, new apps and app update submissions must target Android 14 (API level 34), except for Wear and TV OS apps, which must target Android 13 (API level 33) or higher. Existing apps must target Android 13 (API level 33) or higher to remain available to new users on devices running Android OS higher than your app's target API level.

Update weather app to support API level 34. Best way to do this is to update React Native to latest version to avoid any unexpected behavior. Because changing API level changes how the app behaves.

https://developer.android.com/about/versions/14/behavior-changes-14

**Comment by AnttiRumpunen** [comment]
PR #592

**Comment by AnttiRumpunen** [comment]
minSdkVersion = 23
targetSdkVersion = 34
