### ISSUE TITLE
Check what time is used to show weather icon in forecast's daily tab

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#601]
fmi.fi is using 15:00, app is probably using 14:00. Should be 15:00 regardless of winter/summer time.

![Image](https://github.com/user-attachments/assets/ccf7fc36-5158-48bd-ac82-839a61dd8317)

**Comment by geosaaga** [comment]
14:00 was used before and there was also some incorrect logic for foreign locations: https://github.com/fmidev/weather-app/pull/614
