### ISSUE TITLE
Users are located to africa

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#609]
For some reason latitude/longitude is 0 while the other is correct => user is located to africa. Check what could be the reason...

**Comment by geosaaga** [comment]
Seems that this happens only in iOS, because Android users have not reported issue. Seems to be this one

https://github.com/Agontuk/react-native-geolocation-service/issues/417

**Comment by geosaaga** [comment]
Changed react-native-geolocation-service to react-native-geolocation, because it is developed more actively: https://github.com/fmidev/weather-app/pull/615
