### ISSUE TITLE
App shows "no warnings" for foreign locations

### ISSUE THREAD

**Issue by geosaaga** [fmidev/weather-app#611]
If foreign location is selected the app shows that there are no weather warnings active in warning screen. All days show green status and there is text "Ei voimassa olevia varoituksia". This is incorrect information, because just  weather warning data is missing. Now user may think that are no weather risks for example in his/her holiday location.

Daily warning panel should be hidden if foreign location. Just show warning map for Finland.

The reason for this bug might be international versions. So weather warning data availability should be probably configurable option if the information can't be resolved from warning data.

![Image](https://github.com/user-attachments/assets/3f3a2172-2959-432b-82eb-f2be58c337a0)

**Comment by AnttiRumpunen** [comment]
If apiUrl has defined country, show top section only locations in that defined country. Intl-versions have empty apiUrl and they use CapView to show warnings.
```
 apiUrl: {
      FI: 'XXX',
    },
```

**Comment by geosaaga** [comment]
PR: https://github.com/fmidev/weather-app/pull/663
