### ISSUE TITLE
Add interval-setting for updating data

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#612]
Add interval setting to defaultConfig for the data listed below. Data is updated after this interval has ended. Interval gets resetted if user changes page or closes app.

Weather page
- Next hour (gets updated every full hour)
- Forecast (gets updated every full hour or every 15 minutes)
- Observations (gets updated every full hour or every 5 minutes)

Map page
- depends on which layer is selected, take update interval from timestep value

Warnings page
- Warnings on land areas (gets updated every 5 mins)
- Warnings in the whole Finland (gets updated every 5 mins)
- Add setting also for the CAP warnings (gets updated every 5 mins)

**Comment by geosaaga** [comment]
PR: https://github.com/fmidev/weather-app/pull/623
