### ISSUE TITLE
Polishing queries

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#616]
In 4.1.0 app executed timeseries, autocomplete, warnings -queries which can be optimised in the following way. Idea is to get more hits to cache and remove obsolete queries.

Startup (weather page opens)
- warnings is fetched once with way too many decimals. Use 4 digits instead of 15.
- Location defining uses way too many decimals. Latlon should use 4 digits instead of 15.

Locate self
- same as above. Latlon should use 4 digits instead of 15.

Opening saved/previous location
- fetches observations 4 times, is 2 times enough? (my test notes a bit inaccurate... 2 x with geoid + hourly/daily obs = 4 queries)
- Warnings are fetched twice. Is one time enough?

Searching location
- Autocomplete query is fired from each character. Can there be one second or similar timeout before firing the query? Needs a bit of testing which feels best.

Selected searched location
- warnings is fetched twice. Would once be possible?

Opening map page (time series -layer is selected)
- starttime is too accurate. Can be rounded to next full hour.

Opening Weather page
- warnings is fetched with 15 digit accuracy, change to 4 digits.

---
Notes from heiskanen:
- Observation timeseries -query has cache-control: no-cache. Maybe set to public + max-age=X, where X depends on queried parameter.
- WMS observation -queries have Accept-Encoding: gzip. Is it needed when fetching png/webp images? Not really...
- WMS forecast -queries have ETAG. Timeseries doesn't, why?

**Comment by geosaaga** [comment]
Implemented most of suggested optimatizations in PR https://github.com/fmidev/weather-app/pull/621

Warning data updates and app startup time could be further optimized by adding version number to DynamicConfig #620

Didn't implement or changed these:

- Removed `Cache-Control: no-cache` header, but didn't implement `Maybe set to public + max-age=X, where X depends on queried parameter`. Server should control cache times, not the app.
- `WMS observation -queries have Accept-Encoding: gzip`, these headers are sent by native map libraries (Google Maps, Apple Maps) and can't change those.
- `WMS forecast -queries have ETAG. Timeseries doesn't, why?` Both should have ETAG according to my tests if the same query has been done before. But of course the first query is without ETAG.
