### ISSUE TITLE
Forecast widget (small) - ios

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#652]

**Comment by helgavisuri** [comment]
Content, layout and acute-warning (crisis-banner) and notification example in iOS widget small.

![Frame 49-4](https://github.com/user-attachments/assets/cb4ae727-2958-4a90-b358-0ea8dea442b1)

**Comment by helgavisuri** [comment]
Layout measurements in Figma file dev. mode:
https://www.figma.com/design/yGO3ZG37j9t72Dgw60LN32/FMI?node-id=25-2&m=dev&t=wswyVLVptSUORvCo-1

**Comment by geosaaga** [comment]
PR: https://github.com/fmidev/weather-app/pull/671

Also for #654 and #656
