### ISSUE TITLE
Forecast widget (small) - Android

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#653]

**Comment by helgavisuri** [comment]
Android small widget (content: location, weather icon and temperature):

![Android_widget_small](https://github.com/user-attachments/assets/162da6a9-485a-44fa-bd6f-f25e438e1ece)

**Comment by helgavisuri** [comment]
Layout measurements in Figma file dev. mode:
https://www.figma.com/design/yGO3ZG37j9t72Dgw60LN32/FMI?node-id=25-2&m=dev&t=wswyVLVptSUORvCo-1

**Comment by AnttiRumpunen** [comment]
Deleted as obsolete
