### ISSUE TITLE
Forecast widget (medium) - ios

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#654]

**Comment by helgavisuri** [comment]
Content, layout and acute-warning (crisis-banner) and notification example in iOS widget medium.

Layout measurements in Figma file dev. mode:
https://www.figma.com/design/yGO3ZG37j9t72Dgw60LN32/FMI?node-id=25-2&m=dev&t=wswyVLVptSUORvCo-1
![Frame 50](https://github.com/user-attachments/assets/400c3b27-1fa1-4042-bafc-24aa6992e365)
