### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#655]

**Comment by helgavisuri** [comment]
Android medium widget (content: location, weather icon and temperature)
![Android_widget_medium](https://github.com/user-attachments/assets/48834dd4-1620-46cb-aa6c-d1a0502aacf3)

**Comment by helgavisuri** [comment]
Layout measurements in Figma file dev. mode:
https://www.figma.com/design/yGO3ZG37j9t72Dgw60LN32/FMI?node-id=25-2&m=dev&t=wswyVLVptSUORvCo-1

**Comment by AnttiRumpunen** [comment]
Deleted as obsolete
