### ISSUE TITLE
Forecast widget (large) - ios

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#656]

**Comment by helgavisuri** [comment]
Content, layout and acute-warning (crisis-banner) and notification example in iOS widget large.

Layout measurements in Figma file dev. mode:
https://www.figma.com/design/yGO3ZG37j9t72Dgw60LN32/FMI?node-id=25-2&m=dev&t=wswyVLVptSUORvCo-1
![Frame 52](https://github.com/user-attachments/assets/cfd9b291-6e1b-4842-a586-78d2763c63ba)
