### ISSUE TITLE
Error texts for widgets

### ISSUE THREAD

**Issue by geosaaga** [fmidev/weather-app#665]
Widgets need **Error title** and **Error description** for following situations in finnish, english and swedish.

Titles:

- The widget can't get current location ("Paikannus epäonnistui")
- The widget fails to update weather data ("Säätietojen lataus epäonnistui")
- The weather data is too old ("Säätiedot ovat vanhentuneet")
  - For example in Airplane mode we can show old forecast data for certain time, but eventually the forecast is too old to show
  - Also possible to use "The widget fails to update weather data" texts in this case
- The warning data is not available for current location ("Varoituksia ei ole saatavilla tähän sijaintiin")
- The widget fails to update warning data ("Varoitusten lataus epäonnistui")
- The warning data is too old to show ("Varoitukset ovat vanhentuneet")
  - Same Airplane mode case
  - Also possible to use "The widget fails to update warning data" texts in this case
- TODO: enkuks "Paikannus ei ole sallittu" (android)

Description texts:

- Paikannusta ei ole sallittu. Salli paikannus asetuksista.
- Paikannusta yritetään uudestaan automaattisesti.
- Laite on lentokonetilassa. Säätiedot päivitetään, kun internet-yhteys palautuu.
- Säätiedot päivitetään, kun internet yhteys palautuu.
- Varoitukset ovat saatavilla vain Suomen alueella.
- Laite on lentokonetilassa. Varoitukset päivitetään, kun internet-yhteys palautuu.
- Varoitukset päivitetään, kun internet-yhteys palautuu.

Design example for errors: https://www.figma.com/design/yGO3ZG37j9t72Dgw60LN32/FMI?node-id=233-7487&m=dev

**Comment by LeaSaukkonen** [comment]
Jäin miettimään , että onko tarkoituksenmukaista ilmaista "the Widget" jos teksti näkyy widgetissä?

**Comment by geosaaga** [comment]
Ei ole tarpeen käyttää "widget" sanaa teksteissä

**Comment by LeaSaukkonen** [comment]
Jos teksti näkyy widgetissä niin tässä lista:

1. Paikannus epäonnistui: Location failed
2. Säätietojen lataus epäonnistui: Failed to load weather data
3. Säätiedot ovat vanhentuneet: The weather information is outdated (huom: englannin kielessä weather information/ weather data ovat yksikkömuotoisia (vaikka Suomen kielessä kääntyvät monikkoon), siksi verbi on myös yksikkömuotoinen) 
4. Varoituksia ei ole saatavilla tähän sijaintiin: There are no alerts available for this location tai Alerts are unavailable for this location (ensimmäinen on enemmän jos satavuus ongelma on väliaikainen ja jälkimmäisen nyanssi on että varoituksia ei ole ollenkaan saatavilla)
5. Varoitusten lataus epäonnistui: Failed to load alerts
6. Varoitukset ovat vanhentuneet: The alerts are outdated

**Comment by LeaSaukkonen** [comment]
Huomasin että olen kääntänyt nyt kahdella eri tavalla säätiedot eli kohdassa kaksi on weather data ja kolmanessa on The weather information. Ne ovat lähes sama asia, mutta datan nyanssi on että on kyse yksittäisistä tiedoista kuten lämpötila, tuuli ym ja information on enemmän kokonaisuus. Minusta tämä on ihan maku kysymys kumpaa halutaan käyttää..

**Comment by geosaaga** [comment]
Näihin tarvittaisin vielä pidemmät virheen kuvaukset tai "ohjeet käyttäjälle", jotka ovat designissa

https://www.figma.com/design/yGO3ZG37j9t72Dgw60LN32/FMI?node-id=233-7487

Lisäksi käännökset ruotsiksi.

**Comment by geosaaga** [comment]
@LeaSaukkonen Lisäsin tarvittavat virheen selitykset tiketin kuvaukseen (Description texts).

**Comment by LeaSaukkonen** [comment]
Ja sitten ruotsiksi. En pysty ruotsiksi tunnistamaan nyansseja samalla tasolla kuin englannin kielellä, mutta ehkä Chat GPT siihen pystyy...

Varoitukset:

1. _Paikannus epäonnistui:_ Platsbestämning misslyckades
2. _Säätietojen lataus epäonnistui:_ Misslyckades med att ladda väderdata
3. _Säätiedot ovat vanhentuneet:_ Väderinformationen är inaktuell 
4. _Varoituksia ei ole saatavilla tähän sijaintiin:_ Det finns inga varningar för denna plats.
5. _Varoitusten lataus epäonnistui:_ Misslyckades med att ladda varningar
6. _Varoitukset ovat vanhentuneet:_ Varningarna är inaktuella


Kuvaus tekstit:

1. _Paikannusta ei ole sallittu. Salli paikannus asetuksista:_ Platstjänster är inte tillåtna. Aktivera dem i inställningarna.
2. _Paikannusta yritetään uudestaan automaattisesti:_ Platstjänster försöks automatiskt på nytt.
3. _Laite on lentokonetilassa. Säätiedot päivitetään, kun internet-yhteys palautuu_: Enheten är i flygplansläge. Väderdata uppdateras när internet är tillbaka.
4. _Säätiedot päivitetään, kun internet yhteys palautuu:_ Vädredata uppdateras när internet är tillbaka
5. _Varoitukset ovat saatavilla vain Suomen alueella:_ Varningar är endast tillgängliga i Finland.
6. _Laite on lentokonetilassa. Varoitukset päivitetään, kun internet-yhteys palautuu:_ Enheten är i flygplansläge. Varningarna uppdateras när internet är tillbaka.
7. _Varoitukset päivitetään, kun internet-yhteys palautuu:_ Varningarna uppdateras när internet är tillbaka.
