### ISSUE TITLE
Widget settings screen UI-design for Android

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#667]
Do a UI design for Android once required settings are defined: https://github.com/fmidev/weather-app/issues/666.
IOS doesn't need UI design.

**Comment by helgavisuri** [comment]
Widget settings ui-views for android. 
View on the left: user hasn’t added any locations to favorites. Text and link where user can add favorite locations. Link takes to app’s locations search view.
Information text for the user why permission to use background location service is needed and why. Open location settings-button takes to androids own dialogue / settings view where user can edit permissions.

View on the right:
Favorite locations have been added. Text and link where user can add more favorite locations. Link takes to app’s locations search view.

Open location settings-button ja information text removed (visible only when user hasn’t granted permission to background location service).

https://www.figma.com/design/yGO3ZG37j9t72Dgw60LN32/FMI?node-id=271-6660&t=GdvFHRAY6RjjLQZD-1

![Group 2609154](https://github.com/user-attachments/assets/ded501c9-3cad-402c-92e4-87f5c9d0a302)
