### ISSUE TITLE
Warnings - widget UI designs

### ISSUE THREAD

**Issue by AnttiRumpunen** [fmidev/weather-app#681]
UI designs for current day and five days warnings.

**Comment by helgavisuri** [comment]
Ui designs for current day and 5-day warnings can be found in Figma:
https://www.figma.com/design/yGO3ZG37j9t72Dgw60LN32/FMI?node-id=416-8869&t=0KPzl4PPnR8ttPs1-1

![UI_for_Warning_widgets](https://github.com/user-attachments/assets/369e1229-343c-4eea-b47b-e4cf10d5455e)
